# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Life of Coding
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.lifeOfCoding.com
baseurl:          /

author:
  name:           'Wesley Lin'
  email:           westlinkin@gmail.com

paginate:         1

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
